Repository ohmyform/ohmyform, pull requests merged in 2019-10, with the labels that each got.

#51 Add link to README sections
  README.md
Labels: documentation, enhancement, hacktoberfest

#53 Resolving issue52
  Dockerfile
Labels: hacktoberfest

#45 Modify docker file to use non-root user
  Dockerfile
Labels: enhancement, hacktoberfest

#57 Adding more social
  README.md
Labels: documentation, enhancement, hacktoberfest

#48 Remove grunt-contrib-uglify dependency. It's needed only as dev depen…
  package.json
Labels: bug, hacktoberfest
